"""add profile preferences

Revision ID: 2fb352915a68
Revises: 7e3ab12bba43
Create Date: 2026-09-26 01:26:09.008129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb352915a68'
down_revision = '7e3ab12bba43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=10), server_default='light', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
